name: Continuous integration pipeline
on: push
jobs:
  analyse-code:
    name: Analyse code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
      - name: Install packages and dependencies
        run: |
          python3 -m pip install --upgrade pip==24.0.0
          pip install -r python/requirements.txt
      - name: Flake8 static analysis
        uses: xanderhendriks/flake8-github-action@v1.0.2
        with:
          checkName: 'analyse-code'   # NOTE: this needs to be the same as the job name
  build-application:
    needs: analyse-code
    name: Build application binary
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
        with:
          submodules: 'recursive'
      - name: Build binary
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v5.2.1
          target: esp32
          path: 'esp32'
      - name: Upload esp32 build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: esp32-binaries
          path: |
            **/*.bin
            !esp32/managed_components/**
            !**/CMakeFiles/**
  pyinstaller-win-build:
    needs: build-application
    name: Build fw uploader - Win
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
      - name: Download esp32 build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: esp32-binaries
      - name: Setup python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9.2'
      - name: Install packages and dependencies
        run: |
          python3 -m pip install --upgrade pip==24.0.0
          pip install -r python/requirements.txt
      - name: Build firmware update executable
        run: |
          pyinstaller python/cyd-battery-tester-firmware-update.spec
      - name: Upload firmware update binary
        uses: actions/upload-artifact@v4.3.3
        with:
          name: firmware-update-binary-win
          path: dist/*
  pyinstaller-mac-build:
    needs: build-application
    name: Build fw uploader - Mac
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
      - name: Download esp32 build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: esp32-binaries
      - name: Setup python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9.2'
      - name: Install packages and dependencies
        run: |
          python3 -m pip install --upgrade pip==24.0.0
          pip install -r python/requirements.txt
      - name: Build firmware update executable
        run: |
          pyinstaller python/cyd-battery-tester-firmware-update.spec
      - name: Upload firmware update binary
        uses: actions/upload-artifact@v4.3.3
        with:
          name: firmware-update-binary-mac
          path: dist/*
  release:
    needs: [pyinstaller-win-build, pyinstaller-mac-build]
    if: startsWith(github.ref, 'refs/tags')
    name: Release to Github
    runs-on: ubuntu-22.04
    steps:
      - name: Download win artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: firmware-update-binary-win
          path: dist
      - name: Download mac artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: firmware-update-binary-mac
          path: dist
      - name: Determine version
        id: determine_version
        run: |
          version=$(find dist -name "cyd-battery-tester-firmware-update-win-*" | sed 's/dist\/cyd-battery-tester-firmware-update-win-\(.*\)\.exe/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Release to Github
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: ${{ steps.determine_version.outputs.version }}
          draft: false
          prerelease: false
          artifacts: dist/*
