name: Continuous integration pipeline
on:
  push:
    branches:
      - master
jobs:
  analyse-code:
    name: Analyse code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
      - name: Install packages and dependencies
        run: |
          python3 -m pip install --upgrade pip==24.0.0
          pip install -r python/requirements.txt
      - name: Flake8 static analysis
        uses: xanderhendriks/flake8-github-action@v1.0.2
        with:
          checkName: 'analyse-code'   # NOTE: this needs to be the same as the job name
  build-application:
    needs: analyse-code
    name: Build application binary
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
        with:
          submodules: 'recursive'
      - name: Build binary
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v5.2.1
          target: esp32
          path: 'esp32'
      - name: Upload esp32 build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: esp32-binaries
          path: |
            **/*.bin
            !esp32/managed_components/**
            !**/CMakeFiles/**
  pyinstaller-win-build:
    needs: build-application
    name: Build fw uploader Windows
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
      - name: Download esp32 build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: esp32-binaries
      - name: Test if files are there
        run: |
          dir -R *
      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9.2'
          spec: 'python/cyd-battery-tester-firmware-update.spec'
          requirements: 'python/requirements.txt'
          exe_path: 'python/dist'
          upload_exe_with_name: 'cyd-battery-tester-firmware-update-*.exe'
  pyinstaller-mac-build:
    needs: build-application
    name: Build fw uploader MAC-OS
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
      - name: Download esp32 build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: esp32-binaries
      - name: Test if files are there
        run: |
          ls -R
      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9.2'
          spec: 'python/cyd-battery-tester-firmware-update.spec'
          requirements: 'python/requirements.txt'
          exe_path: 'python/dist'
          upload_exe_with_name: 'cyd-battery-tester-firmware-update-*.exe'
